In [2]:
import numpy as np

In [2]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
x = np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [5]:
x.shape

(39,)

In [14]:
print(x.dtype)

int32


In [15]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sufyan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/sufyan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sufyan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\m

In [159]:
x.ndim

2

In [17]:
bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)

[ True  True False False  True False  True False]


In [27]:
x2d = ([[1, 2, 3], [4, 5, 6]])
print(x2d)

[[1, 2, 3], [4, 5, 6]]


In [19]:
x3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(x3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
x = x[::-1]
print(x)

[[ 6  8 10]
 [ 2  4  6]]


In [41]:
x= np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [42]:
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype('float64') 

print(arr)
print(arr.dtype)

int32
[1. 2. 3. 4. 5.]
float64


In [49]:
arr1 = np.array([[1., 2., 3.],
[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
[7., 2., 12.]])
print ("1st Input  number : ", arr1) 
print ("2nd Input  number : ", arr2) 
    
out_num = np.multiply(arr1, arr2)  
print ("output number : ", out_num)  

1st Input  number :  [[1. 2. 3.]
 [4. 5. 6.]]
2nd Input  number :  [[ 0.  4.  1.]
 [ 7.  2. 12.]]
output number :  [[ 0.  8.  3.]
 [28. 10. 72.]]


In [50]:
arr1 = np.array([[1., 2., 3.],
[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
[7., 2., 12.]])

comparison = arr1 == arr2 
equal_arrays = comparison.all() 
  
print(equal_arrays) 

False


In [51]:
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 7, 9])

In [53]:
a[a % 2 == 1]-1

array([0, 2, 4, 6, 6, 8])

In [58]:
arr = np.arange(10)
np.put(arr, [5,6,7,8],[12])
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [90]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [110]:
arr2d = np.array([[1, 2, 3],
[4, 5, 6], [7, 8, 9]])
arr2d[1,2] =12
arr2d

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [62]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1,0]=64
arr3d


array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [208]:
array = np.arange(9).reshape(3,3)
print(array[0:1])
array.ndim


[[0 1 2]]


2

In [204]:
array = np.arange(9).reshape(3,3)
print(array[1:2])

[[3 4 5]]


In [222]:
array = np.arange(9).reshape(3,3)
print(array[0:2,2:3])


[[2]
 [5]]


In [254]:
from numpy import random

x = random.randint(100, size=(10, 10))
maximum = x.max()
minimum = x.min()
print("max=", maximum, "min=", minimum)


max= 99 min= 0


In [256]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b)) 

[2 4]


In [261]:
p = np.searchsorted(a, np.intersect1d(a, b))
p

array([1, 5], dtype=int64)

In [3]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
newarray = (names !='Will')
print(names[newarray])

['Bob' 'Joe' 'Bob' 'Joe' 'Joe']


In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
newarray = (names !='Will') & (names!='Joe')
print(names[newarray])

['Bob' 'Bob']


In [10]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[ 6.67716295 13.15564601  4.36837106]
 [ 4.07748134 13.28954287  9.36420343]
 [ 3.37165515  4.83669261 11.38761321]
 [ 2.58824312  3.97274218  1.92521272]
 [ 1.31054418  8.5354348  13.10831844]]


In [11]:
rand_arr = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr)

[[[ 2.17914001 15.71317352 10.2962527   3.84229504]
  [ 4.32319807  8.90926937  3.36217061  1.3494161 ]]

 [[ 5.57941235  5.73358559 15.74282217  9.5730986 ]
  [ 4.39676106  3.66159714  7.60345823 10.40031993]]]


In [13]:
x = np.array([[1,2,3]])
np.swapaxes(rand_arr,0,1)

array([[[ 2.17914001, 15.71317352, 10.2962527 ,  3.84229504],
        [ 5.57941235,  5.73358559, 15.74282217,  9.5730986 ]],

       [[ 4.32319807,  8.90926937,  3.36217061,  1.3494161 ],
        [ 4.39676106,  3.66159714,  7.60345823, 10.40031993]]])

In [26]:
x = np.arange(10)
arr= np.sqrt(x)
arr[arr<0.5] = 0
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
a = np.random.randn(12)
b = np.random.randn(12)
np.maximum(a,b)


array([ 1.48929692,  1.16913099,  1.13674854, -0.42790393,  1.33058806,
       -1.00821681,  0.13660561,  0.73588353,  1.71088787,  1.62780431,
        0.49138118,  2.90466375])

In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x = np.unique(names)
print(np.sort(x))

['Bob' 'Joe' 'Will']


In [77]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

newa = [x for x in a if x not in b]
newb = [x for x in b if x not in a]

print(newa, newb)

[1, 2, 3, 4] [6, 7, 8, 9]


In [47]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[2] = newColumn
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [10, 10, 10]])

In [42]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)


array([[ 28.,  64.],
       [ 67., 181.]])

In [40]:
x = np.random.randn(20)
np.cumsum(x)

array([-0.35103719, -0.97712273, -2.52967372, -2.23341645, -1.9498953 ,
       -2.43783851, -3.15239553, -2.72993372, -2.33811115, -2.71175179,
       -2.19182242, -0.1583619 ,  0.96042378,  1.61228308,  1.76654951,
        1.94785412,  2.35924188,  4.27886386,  5.89887008,  5.84759107])